// <auto-generated />
using System;
using Infrastructure.Data.DbContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Infrastructure.Data.Migrations.ModerationContext
{
    [DbContext(typeof(ModerationDbContext))]
    [Migration("20250712163913_changeReleaseBookApproval")]
    partial class changeReleaseBookApproval
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Core.BoundContext.ModerationContext.BookApprovalAggregate.ApprovalDecision", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ChapterApprovalId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("DecisionDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ModeratorId")
                        .HasColumnType("uuid");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("ChapterApprovalId");

                    b.ToTable("ApprovalDecisions", "Moderation");
                });

            modelBuilder.Entity("Core.BoundContext.ModerationContext.BookApprovalAggregate.BookApproval", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AuthorId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("BookId")
                        .HasColumnType("uuid");

                    b.Property<string>("BookTitle")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.ToTable("BookApprovals", "Moderation");
                });

            modelBuilder.Entity("Core.BoundContext.ModerationContext.BookApprovalAggregate.ChapterApproval", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BookApprovalId")
                        .HasColumnType("uuid");

                    b.Property<string>("ChapterContent")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ChapterId")
                        .HasColumnType("uuid");

                    b.Property<int>("ChapterNumber")
                        .HasColumnType("integer");

                    b.Property<string>("ChapterSlug")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ChapterTitle")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<DateTimeOffset>("SubmittedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Version")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("BookApprovalId");

                    b.ToTable("ChapterApproval", "Moderation");
                });

            modelBuilder.Entity("Core.BoundContext.ModerationContext.BookApprovalAggregate.ApprovalDecision", b =>
                {
                    b.HasOne("Core.BoundContext.ModerationContext.BookApprovalAggregate.ChapterApproval", null)
                        .WithMany("Decision")
                        .HasForeignKey("ChapterApprovalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Core.BoundContext.ModerationContext.BookApprovalAggregate.ChapterApproval", b =>
                {
                    b.HasOne("Core.BoundContext.ModerationContext.BookApprovalAggregate.BookApproval", null)
                        .WithMany()
                        .HasForeignKey("BookApprovalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Core.BoundContext.ModerationContext.BookApprovalAggregate.CopyrightChapter", "CopyrightChapter", b1 =>
                        {
                            b1.Property<Guid>("ChapterApprovalId")
                                .HasColumnType("uuid");

                            b1.Property<string>("ChapterContent")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<int>("ChapterNumber")
                                .HasColumnType("integer");

                            b1.Property<string>("ChapterSlug")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)");

                            b1.Property<string>("ChapterTitle")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)");

                            b1.Property<DateTimeOffset>("DateTimeCopyright")
                                .HasColumnType("timestamp with time zone");

                            b1.HasKey("ChapterApprovalId");

                            b1.ToTable("ChapterApproval", "Moderation");

                            b1.WithOwner()
                                .HasForeignKey("ChapterApprovalId");
                        });

                    b.Navigation("CopyrightChapter");
                });

            modelBuilder.Entity("Core.BoundContext.ModerationContext.BookApprovalAggregate.ChapterApproval", b =>
                {
                    b.Navigation("Decision");
                });
#pragma warning restore 612, 618
        }
    }
}
