// <auto-generated />
using System;
using Infrastructure.Data.DbContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Infrastructure.Data.Migrations.ModerationContext
{
    [DbContext(typeof(ModerationDbContext))]
    [Migration("20250531183442_InitModeratorDbContext")]
    partial class InitModeratorDbContext
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Core.BoundContext.ModerationContext.BookApprovalAggregate.ApprovalDecision", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("BookApprovalId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("BookApprovalsId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("DecisionDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsAutomated")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("ModeratorId")
                        .HasColumnType("uuid");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("BookApprovalId");

                    b.ToTable("ApprovalDecisions", "Moderation");
                });

            modelBuilder.Entity("Core.BoundContext.ModerationContext.BookApprovalAggregate.BookApproval", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AuthorId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("BookId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ChapterId")
                        .HasColumnType("uuid");

                    b.Property<string>("ContentHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("CopyrightChapterId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTimeOffset>("SubmittedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Version")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CopyrightChapterId");

                    b.ToTable("BookApprovals", "Moderation");
                });

            modelBuilder.Entity("Core.BoundContext.ModerationContext.BookApprovalAggregate.CopyrightChapter", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AuthorId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("BookId")
                        .HasColumnType("uuid");

                    b.Property<string>("BookTitle")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ChapterContent")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ChapterContentPlainText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ChapterId")
                        .HasColumnType("uuid");

                    b.Property<string>("ChapterTitle")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTimeOffset>("DateTimeCopyright")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.ToTable("CopyrightChapters", "Moderation");
                });

            modelBuilder.Entity("Core.BoundContext.ModerationContext.BookApprovalAggregate.ApprovalDecision", b =>
                {
                    b.HasOne("Core.BoundContext.ModerationContext.BookApprovalAggregate.BookApproval", null)
                        .WithMany("Decision")
                        .HasForeignKey("BookApprovalId");
                });

            modelBuilder.Entity("Core.BoundContext.ModerationContext.BookApprovalAggregate.BookApproval", b =>
                {
                    b.HasOne("Core.BoundContext.ModerationContext.BookApprovalAggregate.CopyrightChapter", "CopyrightChapter")
                        .WithMany()
                        .HasForeignKey("CopyrightChapterId");

                    b.Navigation("CopyrightChapter");
                });

            modelBuilder.Entity("Core.BoundContext.ModerationContext.BookApprovalAggregate.CopyrightChapter", b =>
                {
                    b.OwnsOne("Core.BoundContext.ModerationContext.BookApprovalAggregate.DigitalSignature", "DigitalSignature", b1 =>
                        {
                            b1.Property<Guid>("CopyrightChapterId")
                                .HasColumnType("uuid");

                            b1.Property<string>("SignatureAlgorithm")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)");

                            b1.Property<string>("SignatureValue")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)");

                            b1.Property<DateTimeOffset>("SigningDateTime")
                                .HasColumnType("timestamp with time zone");

                            b1.HasKey("CopyrightChapterId");

                            b1.ToTable("CopyrightChapters", "Moderation");

                            b1.WithOwner()
                                .HasForeignKey("CopyrightChapterId");
                        });

                    b.Navigation("DigitalSignature")
                        .IsRequired();
                });

            modelBuilder.Entity("Core.BoundContext.ModerationContext.BookApprovalAggregate.BookApproval", b =>
                {
                    b.Navigation("Decision");
                });
#pragma warning restore 612, 618
        }
    }
}
