version: '3.7'

services:
  postgres:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - 5434:5432 
    networks:
      - keycloak_network

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    command: start-dev 
    environment:
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres:5432/${POSTGRES_DB}
      KC_DB_USERNAME: ${POSTGRES_USER}
      KC_DB_PASSWORD: ${POSTGRES_PASSWORD}
      KC_HTTP_ENABLED: true
      KC_HEALTH_ENABLED: true
      KK_TO_RMQ_URL: rabbitmq
      KK_TO_RMQ_PORT: 5672
      KK_TO_RMQ_VHOST: /
      KK_TO_RMQ_EXCHANGE: amq.topic
      KK_TO_RMQ_USERNAME: ${RABBITMQ_DEFAULT_USER}
      KK_TO_RMQ_PASSWORD: ${RABBITMQ_DEFAULT_PASS}
      KK_TO_RMQ_USE_TLS: false
    volumes:
      - ./keycloakify-custom/build_keycloak/keycloak-theme-for-kc-all-other-versions.jar:/opt/keycloak/providers/my-theme.jar
      - ./keycloak-plugin/keycloak-to-rabbit-3.0.5.jar:/opt/keycloak/providers/keycloak-to-rabbit-3.0.5.jar
    ports:
      - 8080:8080
    depends_on:
      - postgres
    networks:
      - keycloak_network
  redis:
    image: redis:latest
    ports:
      - 6379:6379
    networks:
      - keycloak_network
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.17.4
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - xpack.security.transport.ssl.enabled=false
      - bootstrap.memory_lock=true
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - keycloak_network
  kibana:
    image: docker.elastic.co/kibana/kibana:8.17.4
    ports:
      - 5601:5601
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    depends_on:
      - elasticsearch
    networks:
      - keycloak_network
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - 5672:5672     
      - 15672:15672
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
    networks:
      - keycloak_network
volumes:
  postgres_data:
    driver: local
  elasticsearch_data:
    driver: local

networks:
  keycloak_network:
    driver: bridge